version: '3.8'

services:
  lushu:
    build:
      context: ..
      dockerfile: Dockerfile
    image: lushu:latest
    container_name: lushu
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ../data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8123
      - DATA_DIR=/app/data
      - SERVER_NO_OPEN=1
